//TODO: fix this so the compiler doesn't strip the template tags
export const sourceCode = [
  '<script lang="ts">',
  "  import { createSignal } from 'tannijs';",
  "",
  "  const [count, setCount] = createSignal(0);",
  "",
  "  function increment() {",
  "    setCount((c) => c + 1);",
  "  }",
  "",
  "  function decrement() {",
  "    setCount((c) => c - 1);",
  "  }",
  "",
  "  function reset() {",
  "    setCount(0);",
  "  }",
  "</script>",
  "",
  "<template>",
  "  <p>{{ count() }}</p>",
  '  <button @click="increment">+ 1</button>',
  '  <button @click="decrement">\u2212 1</button>',
  '  <button @click="reset">Reset</button>',
  "</template>",
].join("\n");

export const compiledCode = [
  "import { createSignal, effect } from 'tannijs';",
  "",
  "export default function Counter() {",
  "  const [count, setCount] = createSignal(0);",
  "",
  "  function increment() {",
  "    setCount((c) => c + 1);",
  "  }",
  "  function decrement() {",
  "    setCount((c) => c - 1);",
  "  }",
  "  function reset() {",
  "    setCount(0);",
  "  }",
  "",
  '  const p = document.createElement("p");',
  "  effect(() => {",
  "    p.textContent = count();",
  "  });",
  "",
  '  const btn1 = document.createElement("button");',
  '  btn1.textContent = "+ 1";',
  '  btn1.addEventListener("click", increment);',
  "",
  '  const btn2 = document.createElement("button");',
  '  btn2.textContent = "\u2212 1";',
  '  btn2.addEventListener("click", decrement);',
  "",
  '  const btn3 = document.createElement("button");',
  '  btn3.textContent = "Reset";',
  '  btn3.addEventListener("click", reset);',
  "",
  "  const _frag = document.createDocumentFragment();",
  "  _frag.append(p, btn1, btn2, btn3);",
  "  return _frag;",
  "}",
].join("\n");
