import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Explicit sidebar so ordering and grouping are controlled by hand
// (rather than autogenerated from the filesystem).
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/your-first-component'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/reactivity',
        'guides/components',
        'guides/template-syntax',
        'guides/directives',
        'guides/styling',
        'guides/lifecycle',
        'guides/tooling',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: ['api/runtime'],
    },
    'roadmap',
  ],
};

export default sidebars;
